export const BUILD_MUNICIPIS = "BUILD_MUNICIPIS";
export const SELECT_MUNICIPI = "SELECT_MUNICIPI";
export const UNSELECT_MUNICIPI = "UNSELECT_MUNICIPI";
export const PREDICT_MUNICIPI = "PREDICT_MUNICIPI";
export const SELECT_DATE = "SELECT_DATE";