/* Sync actions */
export const SELECT_MUNICIPI = "SELECT_MUNICIPI";
export const UNSELECT_MUNICIPI = "UNSELECT_MUNICIPI";
export const SELECT_DATE = "SELECT_DATE";

/* Async actions */
export const BUILD_MUNICIPIS_REQUEST = "BUILD_MUNICIPIS_REQUEST";
export const BUILD_MUNICIPIS_SUCCESS = "BUILD_MUNICIPIS_SUCCESS";
export const BUILD_MUNICIPIS_FAIL = "BUILD_MUNICIPIS_FAIL";

export const PREDICT_MUNICIPI_REQUEST = "PREDICT_MUNICIPI_REQUEST";
export const PREDICT_MUNICIPI_SUCCESS = "PREDICT_MUNICIPI_SUCCESS";
export const PREDICT_MUNICIPI_FAIL = "PREDICT_MUNICIPI_FAIL";